/* GENERATED by pc_port/tools/gen_map7_s03_boss_motion.py — do not edit by hand.
 * Final-boss projectile motion scripts (map7_s03 0x800EC018..0x800EC758),
 * PSX->PC pointer-relocated. Replaces the zero-stubs that crashed both boss
 * variants the instant they attacked (incubator.log / incubus.log). */
typedef struct { int a, b, c, d; } sh_vel16;          /* 16B flat velocity (s_800F3D48_0_0) */
typedef struct { int field_0; void* next_4; int field_8; } sh_scr; /* s_800F3D48_0 (12B PSX, 24B LP64 PC, 12B ILP32 PC) */
#if defined(__SIZEOF_POINTER__) && __SIZEOF_POINTER__ == 4
#define SH_SCR_SZ 12
#else
#define SH_SCR_SZ 24
#endif
#define SH_STR2(x) #x
#define SH_STR(x) SH_STR2(x)
_Static_assert(sizeof(sh_scr) == SH_SCR_SZ, "sh_scr size must match SH_SCR_SZ for the pool offset aliases");
_Static_assert(sizeof(sh_vel16) == 16, "sh_vel16 must be 16B");

sh_vel16 D_800EC018[26] = {
    { 40960, -256, -17920, 0 },
    { 35840, -256, -14080, 0 },
    { 25600, -307, -25600, 0 },
    { 0, 4194352, 262198, 2883608 },
    { 48, 4194352, 262198, 2883608 },
    { 96, 4194352, 262198, 2883608 },
    { 144, 4194352, 262198, 2883608 },
    { 192, 4194352, 262198, 2883608 },
    { 4194304, 4194352, 262198, 2883608 },
    { 4194352, 4194352, 262198, 2883608 },
    { 4194400, 4194352, 262198, 2883608 },
    { 4194448, 4194352, 262198, 2883608 },
    { 4194496, 4194352, 262198, 2883608 },
    { 8388608, 4194352, 262198, 2883608 },
    { 8388656, 4194352, 262198, 2883608 },
    { 8388704, 4194352, 262198, 2883608 },
    { 8388752, 4194352, 262198, 2883608 },
    { 8388800, 4194352, 262198, 2883608 },
    { 0, 4194368, 458809, 2097184 },
    { 64, 4194368, 458809, 2097184 },
    { 128, 4194368, 458809, 2097184 },
    { 192, 4194367, 458809, 2097184 },
    { 4194304, 4194368, 458809, 2097184 },
    { 4194368, 4194368, 458809, 2097184 },
    { 4194432, 4194368, 458809, 2097184 },
    { 4194496, 4194367, 458809, 2097184 },
};

/* vblk2 velocity structs (0x800EC2FC..0x800EC53C); D_800EC34C/3EC are
 * the sentinels game code address-compares. */
sh_vel16 s_velB_00 = { 0, 6291520, 327735, 6291488 };
sh_vel16 s_velB_01 = { 64, 6291520, 327735, 6291488 };
sh_vel16 s_velB_02 = { 128, 6291520, 327735, 6291488 };
sh_vel16 s_velB_03 = { 192, 6291519, 327735, 6291488 };
sh_vel16 s_velB_04 = { 6291456, 6291520, 327735, 6291488 };
sh_vel16 D_800EC34C = { 6291520, 6291520, 327735, 6291488 };
sh_vel16 s_velB_06 = { 6291584, 6291520, 327735, 6291488 };
sh_vel16 s_velB_07 = { 6291648, 6291519, 327735, 6291488 };
sh_vel16 s_velB_08 = { 0, 6291488, 393272, 6291472 };
sh_vel16 s_velB_09 = { 32, 6291488, 393272, 6291472 };
sh_vel16 s_velB_10 = { 64, 6291488, 393272, 6291472 };
sh_vel16 s_velB_11 = { 96, 6291488, 393272, 6291472 };
sh_vel16 s_velB_12 = { 128, 6291488, 393272, 6291472 };
sh_vel16 s_velB_13 = { 160, 6291488, 393272, 6291472 };
sh_vel16 s_velB_14 = { 192, 6291488, 393272, 6291472 };
sh_vel16 D_800EC3EC = { 224, 6291487, 393272, 6291472 };
sh_vel16 s_velB_16 = { 6291456, 6291488, 393272, 6291472 };
sh_vel16 s_velB_17 = { 6291488, 6291488, 393272, 6291472 };
sh_vel16 s_velB_18 = { 6291520, 6291488, 393272, 6291472 };
sh_vel16 s_velB_19 = { 6291552, 6291488, 393272, 6291472 };
sh_vel16 s_velB_20 = { 6291584, 6291488, 393272, 6291472 };
sh_vel16 s_velB_21 = { 6291616, 6291488, 393272, 6291472 };
sh_vel16 s_velB_22 = { 6291648, 6291488, 393272, 6291472 };
sh_vel16 s_velB_23 = { 6291680, 6291487, 393272, 6291472 };
sh_vel16 s_velB_24 = { 10485760, 4194336, 393272, 4194320 };
sh_vel16 s_velB_25 = { 10485792, 4194336, 393272, 4194320 };
sh_vel16 s_velB_26 = { 10485824, 4194336, 393272, 4194320 };
sh_vel16 s_velB_27 = { 10485856, 4194336, 393272, 4194320 };
sh_vel16 s_velB_28 = { 10485888, 4194336, 393272, 4194320 };
sh_vel16 s_velB_29 = { 10485920, 4194336, 393272, 4194320 };
sh_vel16 s_velB_30 = { 10485952, 4194336, 393272, 4194320 };
sh_vel16 s_velB_31 = { 10485984, 4194335, 393272, 4194320 };
sh_vel16 s_velB_32 = { 12582912, 3932192, 327735, 3932176 };
sh_vel16 s_velB_33 = { 12582944, 3932192, 327735, 3932176 };
sh_vel16 s_velB_34 = { 12582976, 3932192, 327735, 3932176 };
sh_vel16 s_velB_35 = { 12583008, 3932192, 327735, 3932176 };

sh_vel16 D_800EC798[7] = {
    { 568524, -11059, -400998, 0 },
    { 572211, -13926, -398131, 0 },
    { 569753, -16384, -397721, 0 },
    { 572620, -16384, -397721, 0 },
    { 574259, -13926, -398131, 0 },
    { 575488, -11059, -400998, 0 },
    { 572211, -15564, -401408, 0 },
};

int D_800EC758[3] = { 0, 819, 1638 };
int D_800EC764[3] = { 8192, 12288, 10240 };

sh_scr D_800EC1B8[27] = {
    { 0, (void*)&D_800EC018[18], 0 },
    { 0, (void*)&D_800EC018[19], 0 },
    { 0, (void*)&D_800EC018[20], 0 },
    { 0, (void*)&D_800EC018[21], 0 },
    { 0, (void*)&D_800EC018[22], 0 },
    { 0, (void*)&D_800EC018[23], 0 },
    { 0, (void*)&D_800EC018[24], 0 },
    { 0, (void*)&D_800EC018[25], 0 },
    { 0, (void*)&D_800EC1B8[0], 2 },
    { 1, (void*)&D_800EC018[3], 0 },
    { 1, (void*)&D_800EC018[4], 0 },
    { 1, (void*)&D_800EC018[5], 0 },
    { 1, (void*)&D_800EC018[6], 0 },
    { 4, (void*)&D_800EC018[7], 0 },
    { 0, (void*)&D_800EC1B8[9], 2 },
    { 1, (void*)&D_800EC018[8], 0 },
    { 1, (void*)&D_800EC018[9], 0 },
    { 1, (void*)&D_800EC018[10], 0 },
    { 1, (void*)&D_800EC018[11], 0 },
    { 4, (void*)&D_800EC018[12], 0 },
    { 0, (void*)&D_800EC1B8[15], 2 },
    { 1, (void*)&D_800EC018[13], 0 },
    { 1, (void*)&D_800EC018[14], 0 },
    { 1, (void*)&D_800EC018[15], 0 },
    { 1, (void*)&D_800EC018[16], 0 },
    { 4, (void*)&D_800EC018[17], 0 },
    { 0, (void*)&D_800EC1B8[21], 2 },
};

sh_scr D_800EC53C[45] = {
    { 0, (void*)&s_velB_32, 0 },
    { 0, (void*)&s_velB_33, 0 },
    { 0, (void*)&s_velB_34, 0 },
    { 0, (void*)&s_velB_35, 0 },
    { 0, (void*)&s_velB_35, 0 },
    { 0, (void*)&s_velB_35, 0 },
    { 0, (void*)&s_velB_35, 0 },
    { 0, (void*)&s_velB_35, 0 },
    { 0, (void*)&D_800EC53C[0], 2 },
    { 0, (void*)&s_velB_16, 0 },
    { 0, (void*)&s_velB_17, 0 },
    { 0, (void*)&s_velB_18, 0 },
    { 0, (void*)&s_velB_19, 0 },
    { 0, (void*)&s_velB_20, 0 },
    { 0, (void*)&s_velB_21, 0 },
    { 0, (void*)&s_velB_22, 0 },
    { 0, (void*)&s_velB_23, 0 },
    { 0, (void*)&D_800EC53C[9], 2 },
    { 0, (void*)&s_velB_24, 0 },
    { 0, (void*)&s_velB_25, 0 },
    { 0, (void*)&s_velB_26, 0 },
    { 0, (void*)&s_velB_27, 0 },
    { 0, (void*)&s_velB_28, 0 },
    { 0, (void*)&s_velB_29, 0 },
    { 0, (void*)&s_velB_30, 0 },
    { 0, (void*)&s_velB_31, 0 },
    { 0, (void*)&D_800EC53C[18], 2 },
    { 0, (void*)&s_velB_00, 0 },
    { 0, (void*)&s_velB_01, 0 },
    { 0, (void*)&s_velB_02, 0 },
    { 0, (void*)&s_velB_03, 0 },
    { 0, (void*)&s_velB_04, 0 },
    { 0, (void*)&D_800EC34C, 0 },
    { 0, (void*)&s_velB_06, 0 },
    { 0, (void*)&s_velB_07, 0 },
    { 0, (void*)&D_800EC53C[27], 1 },
    { 0, (void*)&s_velB_08, 0 },
    { 0, (void*)&s_velB_09, 0 },
    { 0, (void*)&s_velB_10, 0 },
    { 0, (void*)&s_velB_11, 0 },
    { 0, (void*)&s_velB_12, 0 },
    { 0, (void*)&s_velB_13, 0 },
    { 0, (void*)&s_velB_14, 0 },
    { 0, (void*)&D_800EC3EC, 0 },
    { 0, (void*)&D_800EC53C[36], 1 },
};

/* Offset aliases into the single pool array (exact, no padding). The byte
 * stride is SH_SCR_SZ (sizeof sh_scr) so this is correct on LP64 and ILP32. */
__asm__(".global D_800EC5A8\n.set D_800EC5A8, D_800EC53C+" SH_STR(9*SH_SCR_SZ) "\n");
__asm__(".global D_800EC614\n.set D_800EC614, D_800EC53C+" SH_STR(18*SH_SCR_SZ) "\n");
__asm__(".global D_800EC680\n.set D_800EC680, D_800EC53C+" SH_STR(27*SH_SCR_SZ) "\n");
__asm__(".global D_800EC6EC\n.set D_800EC6EC, D_800EC53C+" SH_STR(36*SH_SCR_SZ) "\n");

/* The 3 boss-attack script entry points (func_800DA9F8 copies these into a
 * local and assigns ptr->ptr_0 = D_800CAE30[arg1]). PSX rodata held
 * { &D_800EC1B8[9], &D_800EC1B8[15], &D_800EC1B8[21] } (raw 0x800EC224/26C/2B4).
 * Zero-stubbed it was 3 NULLs, so every spawned projectile got ptr_0 == NULL
 * -> func_800D88E8 NULL-deref (incubus/incubator boss crash). This is the real
 * producer; the func_800D947C/952C ptr_0 seeds only masked un-spawned entries. */
void* D_800CAE30[3] = {
    (void*)&D_800EC1B8[9],
    (void*)&D_800EC1B8[15],
    (void*)&D_800EC1B8[21],
};

