#!/usr/bin/env python3
"""Russian for everything the Team Raccoon disc could not supply.

make_ru_template.py fills the script, the items and the retail menus from the
disc. What is left is the text the PC port added, which existed on no 1999
disc: the PC Options rows, the F10 Quick Options menu, the Controls panel and
the confirm boxes. Those are written here and merged in by make_ru_lang.py.

Two different renderers, two different rules:

  MENU.*  draws with the GAME font. On the Cyrillic atlas the Latin capitals
          are gone (they hold uppercase Cyrillic), so these must be Cyrillic
          only -- no "VSync", no "FPS". Wording is taken from the port's own
          lang_ru_menu.inc wherever it already has the row, so a Russian disc
          and the Russian pack read the same. Budgets are the label column.

  QUICK.* draws with a TrueType font, so it takes any letter: key names
          (Esc, PgUp, F10), Latin acronyms and Ё are all fine there.
"""

# --- PC Options and the other game-font rows (Cyrillic only) ---------------
MENU = {
    # Save/load screen, brightness and controller presets: raw literals
    # at their draw site, so no translator could reach them until the
    # extractor learned about them. The trailing padding on the
    # brightness labels aligns the value after them.
    '\x07________New_save': '\x07____Новая_запись',
    '\x07____Create_new_file': '\x07___Создать_файл',
    '\x07____File_is_damaged': '\x07___Файл_повреждён',
    '\x07Out_of_blocks': '\x07Нет_места',
    '\x07No_data_file': '\x07Нет_данных',
    '\x07Yes__________No': '\x07Да__________Нет',
    'Bus': 'Автобус',
    'BRIGHTNESS': 'ЯРКОСТЬ_______',
    'CONTRAST': 'КОНТРАСТ_____',
    'SATURATION': 'НАСЫЩЕНИЕ___',
    'USER': 'СВОЙ',
    'TYPE_1': 'ТИП_1',
    'TYPE_2': 'ТИП_2',
    'TYPE_3': 'ТИП_3',

    # '=' is a long dash on this atlas (consolgames moved it), and the disc's
    # own On/Off brackets are single hyphens, so match those.
    '==Use_OK==':  '-Можно-',
    '==Use_OK?==': '-Можно?-',
    '==Use_NG==':  '-Нельзя-',
    # The disc has nothing readable at this one; it read back as a stray 'х'.
    'Stock:':      'Запас:',

    'PC_Options':     'Опции_ПК',
    '[R]_Reset':      '[Р]_Сброс',
    'Resolution':     'Разрешение',
    'Window_Mode':    'Режим_окна',
    'VSync':          'Вертик._синхр.',
    'Texture_Filter': 'Фильтрация',
    'PGXP':           'Коррекция',
    'Antialiasing':   'Сглаживание',
    'Post_Process':   'Постобработка',
    'Tone_Mapping':   'Тонмаппинг',
    'Next_Page':      'След._страница',
    'Prev_Page':      'Пред._страница',
    'Back':           'Назад',

    'Beam_Intensity':  'Яркость_луча',
    'Beam_Size':       'Размер_луча',
    'Fog_Strength':    'Плотн._тумана',
    'Disable_Culling': 'Без_отсечения',
    'FPS_Limit':       'Лимит_кадров',
    'FMV_Movie_Vol':   'Громк._видео',
    'Weather_Rate':    'Частота_погоды',

    '2D_Controls':       'Плоское_упр.',
    'Mouse_Sensitivity': 'Чувств._мыши',
    'Pad_Sensitivity':   'Чувств._геймпада',
    'Invert_Mouse_Y':    'Инверсия_мыши',
    'Invert_Pad_Y':      'Инверсия_геймпада',
    'Bullet_Decals':     'Следы_пуль',

    'Aim_Assist':        'Помощь_прицела',
    'First_Person_FOV':  'Обзор_от_1-го_лица',
    'Third_Person_FOV':  'Обзор_от_3-го_лица',
    'OTS_FOV':           'Обзор_из-за_плеча',
    'Aim_Zoom':          'Приближение',
    'OTS_Aim_Zoom':      'Прибл._из-за_плеча',
    'OTS_Aim_In_TPS':    'Прицел_из-за_плеча',
    'Camera_Collision':  'Коллизия_камеры',

    'Minimap':          'Миникарта',
    'Minimap_Scale':    'Размер_миникарты',
    'Minimap_Corner':   'Угол_миникарты',
    'Minimap_Opacity':  'Прозрачность',
    'Minimap_Reqs_Map': 'Нужна_карта',
    'Text_Size':        'Размер_текста',

    # Options > Language. The row draws these with the active atlas, so on the
    # Cyrillic one the Latin names would lose their capitals.
    'English':  'Английский',
    'German':   'Немецкий',
    'French':   'Французский',
    'Spanish':  'Испанский',
    'Italian':  'Итальянский',
    # Both of these are reachable on any disc now, so the row needs them.
    'Japanese': 'Японский',
    'Chinese':  'Китайский',
    'Low_HP_Glow':      'Свечение_ран',
    'Crosshair':        'Прицел',
    'Crosshair_Size':   'Размер_прицела',

    # Values. "Анизо 2х" uses the Cyrillic х, the usual Russian way to write
    # a multiplier, because the Latin x is a lowercase-only cell here.
    'Windowed':   'В_окне',
    'Fullscreen': 'Полный_экран',
    'Borderless': 'Без_рамки',
    'Dither':     'Дизеринг',
    'Bilinear':   'Билинейный',
    'Trilinear':  'Трилинейный',
    'Aniso_2x':   'Анизо_2х',
    'Aniso_4x':   'Анизо_4х',
    'Aniso_8x':   'Анизо_8х',
    'Aniso_16x':  'Анизо_16х',
    'CRT':         'ЭЛТ',
    'Scanlines':   'Строки',
    'Vignette':    'Виньетка',
    'Color_Grade': 'Цветокор.',
    'Film_Grain':  'Зерно',
    'Sharpen':     'Резкость',
    'PSX_Retro':   'Ретро',
    'Cinematic':   'Кино',
    'Reinhard':    'Рейнхард',
    'ACES':        'Эйсес',
    'Filmic':      'Плёночный',
    'Classic':     'Классика',
    'C_+_Shadows': 'К_+_тени',
    'Modern':      'Совр.',
    'M_+_Shadows': 'С_+_тени',
    'Top_L':       'Верх_Л',
    'Top_R':       'Верх_П',
    'Bottom_L':    'Низ_Л',
    'Bottom_R':    'Низ_П',
    'Square':      'Квадрат',
    'Circle':      'Круг',
    '30_Hz':       '30_Гц',
    '60_Hz':       '60_Гц',
}

# --- Quick Options, Cheats/Debug, Controls panel, confirm boxes ------------
QUICK = {
    'Graphics': 'Графика',
    'Lighting & Effects': 'Свет и эффекты',
    'HUD': 'Интерфейс',
    'Audio': 'Звук',
    'View': 'Вид',
    'Cheats': 'Читы',
    'Cheat Actions': 'Действия читов',
    'Debug': 'Отладка',
    'Debug Actions': 'Действия отладки',
    'Controls': 'Управление',
    'QUICK OPTIONS': 'БЫСТРЫЕ НАСТРОЙКИ',
    'Classic': 'Классическая',
    'Thirdperson': 'От третьего лица',
    'Over-the-Shoulder': 'Из-за плеча',
    'Firstperson': 'От первого лица',
    'Previous': 'Назад',
    'Next': 'Вперёд',
    'Close': 'Закрыть',

    'Shadow Resolution': 'Разрешение теней',
    'Dream Blur': 'Размытие сна',
    'Dream Blur Strength': 'Сила размытия сна',
    'Speaker Layout': 'Расположение колонок',
    'Music Volume': 'Громкость музыки',
    'Effects Volume': 'Громкость эффектов',
    'Disable D-pad for Movement': 'Крестовина не для ходьбы',
    'Edit Keybinds': 'Настроить клавиши',
    'Control Type': 'Тип настройки',
    'Aspect Trim': 'Правка пропорций',
    'FOV': 'Обзор',
    'Vertical Shift': 'Сдвиг по вертикали',
    'Cutscene Shift': 'Сдвиг в роликах',
    'Reset View Settings': 'Сбросить настройки вида',
    'Horizontal FOV': 'Обзор по горизонтали',
    'Vertical FOV': 'Обзор по вертикали',
    'Pixel Aspect': 'Форма пикселя',
    'OTS Aim (while in TPS)': 'Прицел из-за плеча (в режиме 3-го лица)',
    'Aim Zoom': 'Приближение при прицеливании',
    'Rest X (left/right)': 'Покой X (влево/вправо)',
    'Rest Y (up/down)': 'Покой Y (вверх/вниз)',
    'Aim X (left/right)': 'Прицел X (влево/вправо)',
    'Aim Y (up/down)': 'Прицел Y (вверх/вниз)',
    'Head X (left/right)': 'Голова X (влево/вправо)',
    'Head Y (up/down)': 'Голова Y (вверх/вниз)',
    'Head Z (fwd/back)': 'Голова Z (вперёд/назад)',
    'Melee Swing Pullback': 'Замах в ближнем бою',

    'Auto': 'Авто',
    'Stereo': 'Стерео',
    'Quad': 'Квадро',
    'HRTF': 'HRTF',
    'Simple': 'Простая',
    'Advanced': 'Расширенная',
    '{n} rows': '{n} строк',
    '(default)': '(по умолчанию)',
    '(off)': '(выкл)',
    '(simple)': '(простая)',

    'Up/Down select': 'Вверх/Вниз выбор',
    'Left/Right adjust': 'Влево/Вправо значение',
    'Q/E or PgUp/PgDn page': 'Q/E или PgUp/PgDn страница',
    'Drag the title to move': 'Тяните заголовок, чтобы передвинуть',
    '{key} or Esc close': '{key} или Esc закрыть',
    '* needs restart': '* нужен перезапуск',

    'God mode': 'Режим бога',
    'Infinite ammo': 'Бесконечные патроны',
    'Noclip': 'Сквозь стены',
    'Enemies ignore Harry': 'Враги не видят Гарри',
    'Unlimited enemies': 'Бесконечные враги',
    'Big head mode': 'Большая голова',
    'Handgun bullets +15': 'Патроны к пистолету +15',
    'Hunting rifle +30': 'Охотничье ружьё +30',
    'Shotgun +30': 'Дробовик +30',
    'Kill nearby enemies': 'Убить врагов рядом',
    'Play as': 'Играть за',
    'Free camera': 'Свободная камера',
    'Allow console': 'Разрешить консоль',
    'Collision visualizer': 'Показ коллизий',
    'Keyframe viewer (K)': 'Просмотр кадров (K)',
    'Fast forward (Ctrl+F5)': 'Ускорение (Ctrl+F5)',
    'Wireframe (Ctrl+F1)': 'Каркас (Ctrl+F1)',
    'No textures (Ctrl+F2)': 'Без текстур (Ctrl+F2)',
    'Starting map': 'Начальная карта',
    'Spawn': 'Создать',
    'Log Harry position': 'Записать позицию Гарри',
    'Log camera shot': 'Записать ракурс камеры',
    'Kill Harry': 'Убить Гарри',
    '(not in this map)': '(нет на этой карте)',

    'CONTROLS': 'УПРАВЛЕНИЕ',
    'Move Up': 'Вперёд',
    'Move Down': 'Назад',
    'Turn Left': 'Поворот влево',
    'Turn Right': 'Поворот вправо',
    'Action / Shoot': 'Действие / Выстрел',
    'Flashlight': 'Фонарик',
    'Map': 'Карта',
    'Run': 'Бег',
    'Sidestep Left': 'Шаг влево',
    'Sidestep Right': 'Шаг вправо',
    'Aim': 'Прицел',
    'Pause': 'Пауза',
    'Inventory': 'Инвентарь',
    'Reload': 'Перезарядка',
    'Cycle Weapons': 'Смена оружия',
    'Quick Heal': 'Быстрое лечение',
    'Quick Turn': 'Быстрый разворот',
    'Rear Look': 'Взгляд назад',
    'Change Camera': 'Сменить камеру',
    'Swap Shoulder': 'Сменить плечо',
    'Quick Options': 'Быстрые настройки',
    'Quick Save': 'Быстрое сохранение',
    'Quick Load': 'Быстрая загрузка',
    'Classic (Default)': 'Классическая (по умолчанию)',
    'Thirdperson Shooter': 'Шутер от третьего лица',
    'Over the Shoulder': 'Из-за плеча',
    'First Person': 'От первого лица',
    'Editing: alternate camera binds (current camera: {camera})':
        'Настройка: клавиши других камер (текущая камера: {camera})',
    'Editing: classic camera binds': 'Настройка: клавиши классической камеры',
    'Controller: {name}': 'Геймпад: {name}',
    'Controller: none connected': 'Геймпад: не подключён',
    'Action': 'Действие',
    'Keyboard': 'Клавиатура',
    'Keyboard 2': 'Клавиатура 2',
    'Controller': 'Геймпад',
    'Controller 2': 'Геймпад 2',
    'Reset to Defaults': 'Сбросить по умолчанию',
    'Press a key...': 'Нажмите клавишу...',
    'Press a button...': 'Нажмите кнопку...',
    'more above': 'ещё выше',
    'more below': 'ещё ниже',
    'Press a key for {action}': 'Нажмите клавишу для «{action}»',
    'Press a key or mouse button for {action}': 'Нажмите клавишу или кнопку мыши для «{action}»',
    'Press a controller button for {action}': 'Нажмите кнопку геймпада для «{action}»',
    'Esc to cancel': 'Esc для отмены',
    'Esc, or wait a few seconds, to cancel': 'Esc или подождите несколько секунд для отмены',
    'Enter / A: rebind': 'Enter / A: назначить',
    'Delete / X: clear': 'Delete / X: очистить',
    'Esc / B: back': 'Esc / B: назад',
    'Mouse: click a bind to change it, right-click to clear. Orange = used twice.':
        'Мышь: щелчок по клавише меняет её, правый щелчок очищает. Оранжевый = назначено дважды.',
    'Left Stick': 'Левый стик',
    'Left Mouse': 'Левая кнопка мыши',
    'Right Mouse': 'Правая кнопка мыши',
    'Middle Mouse': 'Средняя кнопка мыши',
    'Wheel Up': 'Колесо вверх',
    'Wheel Down': 'Колесо вниз',
    'D-pad Up': 'Крестовина вверх',
    'D-pad Down': 'Крестовина вниз',
    'D-pad Left': 'Крестовина влево',
    'D-pad Right': 'Крестовина вправо',

    'RESET CONTROLS': 'СБРОС УПРАВЛЕНИЯ',
    'Reset the classic camera binds to their defaults?':
        'Сбросить клавиши классической камеры по умолчанию?',
    'Reset the alternate camera binds to their defaults?':
        'Сбросить клавиши других камер по умолчанию?',
    'RESET SETTINGS': 'СБРОС НАСТРОЕК',
    'Reset all PC options to their defaults?': 'Сбросить все настройки ПК по умолчанию?',
    'Yes': 'Да',
    'No': 'Нет',
    'Left/Right select': 'Влево/Вправо выбор',
    '[OK] confirm': '[OK] подтвердить',
    '[Cancel] back': '[Отмена] назад',
}

# --- Gaps in the disc text itself ------------------------------------------
# Team Raccoon left item 32's NAME empty (its description is there and reads
# "Ключ, открывающий дверь в вестибюль"), so the inventory showed a blank.
OTHER = {
    'ITEM_NAME.32': 'Ключ_от_вестибюля',
}
