"""Emit the launcher's XaTable.cs from g_XaItemData in sound_data.c.

The Voices tool needs each line's XA file, start sector and authored length
(VSync frames) to find and decode it on the disc. Run after any change to the
table: python pc_port/tools/gen_xa_table.py
"""
import re, os
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
src = open(os.path.join(root, "src/bodyprog/sound/sound_data.c"), encoding="utf-8", errors="replace").read()
m = re.search(r"g_XaItemData\[727\]\s*=\s*\{(.*?)\n\};", src, re.S)
rows = re.findall(r"\{\s*([^}]*?)\s*\}", m.group(1))
items = []
for r in rows:
    f = [x.strip() for x in r.split(",")]
    items.append((int(f[0], 0), int(f[4], 0), int(f[6], 0)))
assert len(items) == 727, len(items)
out = os.path.join(root, "pc_port/launcher/SilentHillPC_Launcher/XaTable.cs")
with open(out, "w", encoding="utf-8", newline="\r\n") as o:
    o.write("// GENERATED by pc_port/tools/gen_xa_table.py from src/bodyprog/sound/sound_data.c. Do not edit.\n")
    o.write("namespace SilentHillPC_Launcher\n{\n")
    o.write("    /// <summary>The game's XA voice-line table (g_XaItemData): XA file index (1..9),\n")
    o.write("    /// start sector within that file, authored length in VSync frames.</summary>\n")
    o.write("    internal static class XaTable\n    {\n")
    o.write("        public struct Item\n        {\n            public byte File;\n            public int Sector;\n            public int Frames;\n")
    o.write("            public Item(byte f, int s, int fr) { File = f; Sector = s; Frames = fr; }\n        }\n\n")
    o.write("        public static readonly Item[] Items = new Item[]\n        {\n")
    for i, (f, s, fr) in enumerate(items):
        o.write("            new Item(%d, %d, %d),%s\n" % (f, s, fr, (" // %d" % i) if i % 50 == 0 else ""))
    o.write("        };\n    }\n}\n")
print("wrote", out, len(items), "items")
