# -*- coding: utf-8 -*-
"""Emit gamedata/ra/sym.extra.txt: the D_<address> globals the decomp defines
but its sym files never name.

The RetroAchievements address map pairs configs/USA/sym.*.txt with symbols
resolved BY NAME at runtime. Where the sym file has no entry for an address, the
preceding symbol's span is inferred all the way to the next named one and
swallows it, so the read lands on unrelated native memory.

That is what kept the star/rank achievements (Harry the Okay/Good/Great/Best)
from ever firing: the whole `.bss, ranking` subsegment at 0x800C48A0 is unnamed
in the sym file, so 0x800C48B0 (clearGameCount) and 0x800C48B5 (the ranking
score) resolved into g_Demo_IsLoadingChunks' inferred span and read 0.

Those globals DO exist natively, exported, and their names encode their own PSX
addresses -- `u8 D_800C48B0;` in src/bodyprog/ranking.c. So the fix is entirely
mechanical: find every file-scope D_XXXXXXXX definition in the tree and write it
out as a sym entry. Nothing is invented; a name that does not resolve at runtime
is simply skipped by the loader, exactly like the 829 that already do not.
"""
import io, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'pc_port', 'assets', 'gamedata', 'ra', 'sym.extra.txt')
EXISTING = [os.path.join(ROOT, 'configs', 'USA', 'sym.bodyprog.txt'),
            os.path.join(ROOT, 'configs', 'USA', 'sym.main.txt')]

# A file-scope definition: no leading whitespace, not static/extern/typedef, and
# the declarator is D_ followed by exactly 8 hex digits.
DEF = re.compile(r'^(?!\s)(?!static\b)(?!extern\b)(?!typedef\b)'
                 r'[A-Za-z_][\w \t\*]*?\bD_([0-9A-Fa-f]{8})\s*(\[|;|=)')

known = set()
for path in EXISTING:
    if not os.path.exists(path):
        continue
    with io.open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            m = re.match(r'\s*([A-Za-z_][\w]*)\s*=\s*0x([0-9A-Fa-f]+)\s*;', line)
            if m:
                known.add(int(m.group(2), 16))

found = {}
for base, _dirs, files in os.walk(SRC):
    for fn in files:
        if not fn.endswith(('.c', '.inc')):
            continue
        path = os.path.join(base, fn)
        try:
            text = io.open(path, encoding='utf-8', errors='replace').read()
        except OSError:
            continue
        for line in text.split('\n'):
            m = DEF.match(line)
            if not m:
                continue
            addr = int(m.group(1), 16)
            if (addr & 0xFF000000) != 0x80000000:
                continue
            if addr in known:
                continue
            rel = os.path.relpath(path, ROOT).replace('\\', '/')
            found.setdefault(addr, rel)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
w = io.open(OUT, 'w', encoding='utf-8', newline='\n')
w.write('// GENERATED by pc_port/tools/gen_ra_extra_syms.py -- do not edit.\n')
w.write('//\n')
w.write('// D_<address> globals the decomp defines but configs/USA/sym.*.txt never\n')
w.write('// names. Without these the RetroAchievements address map lets the preceding\n')
w.write('// symbol\'s inferred span swallow them, and the set reads unrelated memory --\n')
w.write('// which is why the whole .bss ranking subsegment (0x800C48A0) read 0 and the\n')
w.write('// star achievements could never fire.\n')
w.write('//\n')
w.write('// The name encodes the address, so nothing here is guessed. Names that do not\n')
w.write('// resolve at runtime are skipped by the loader.\n\n')
for addr in sorted(found):
    w.write('D_%08X = 0x%08X; // %s\n' % (addr, addr, found[addr]))
w.close()
print('wrote %d symbols to %s' % (len(found), OUT))
rank = [a for a in found if 0x800C48A0 <= a < 0x800C48E0]
print('ranking subsegment covered: %d symbols' % len(rank))
