"""Emit the launcher's MsgTable.cs from the English script JSON.

The Voices tool's "Text boxes" list needs every map message key (the same
"MAPx_Syy.N" / "COMMON.N" keys the language packs and pc_msg_voice.c use) with
readable text. Run after the script changes:
    python pc_port/tools/gen_msg_table.py
"""
import json, os, re
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
src = os.path.join(root, "pc_port/localization/SilentHill_EN_raw.json")
with open(src, encoding="utf-8") as f:
    data = json.load(f)

# Same order as s_MapNames in pc_port/src/lang_pack.c (e_MapIdx order).
MAPS = ["COMMON",
        "MAP0_S00", "MAP0_S01", "MAP0_S02",
        "MAP1_S00", "MAP1_S01", "MAP1_S02", "MAP1_S03", "MAP1_S04", "MAP1_S05", "MAP1_S06",
        "MAP2_S00", "MAP2_S01", "MAP2_S02", "MAP2_S03", "MAP2_S04",
        "MAP3_S00", "MAP3_S01", "MAP3_S02", "MAP3_S03", "MAP3_S04", "MAP3_S05", "MAP3_S06",
        "MAP4_S00", "MAP4_S01", "MAP4_S02", "MAP4_S03", "MAP4_S04", "MAP4_S05", "MAP4_S06",
        "MAP5_S00", "MAP5_S01", "MAP5_S02", "MAP5_S03",
        "MAP6_S00", "MAP6_S01", "MAP6_S02", "MAP6_S03", "MAP6_S04", "MAP6_S05",
        "MAP7_S00", "MAP7_S01", "MAP7_S02", "MAP7_S03",
        "MAPT_S00", "MAPX_S00"]
order = {m: i for i, m in enumerate(MAPS)}

def clean(t):
    t = re.sub(r"~J\d\([\d.]+\)", "", t)
    t = t.replace("~N", " ")
    t = re.sub(r"~[A-Za-z]\d*", "", t)
    t = t.replace("\t", "").replace("\n", " ").replace("_", " ")
    return re.sub(r"\s+", " ", t).strip()

def cs(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

items = []
for key, text in data.items():
    m = re.match(r"^(COMMON|MAP[0-9TX]_S\d\d)\.(\d+)$", key)
    if not m or m.group(1) not in order:
        continue
    items.append((order[m.group(1)], int(m.group(2)), key, clean(text)))
items.sort()

out = os.path.join(root, "pc_port/launcher/SilentHillPC_Launcher/MsgTable.cs")
with open(out, "w", encoding="utf-8-sig", newline="\r\n") as o:
    o.write("// GENERATED by pc_port/tools/gen_msg_table.py from pc_port/localization/SilentHill_EN_raw.json. Do not edit.\n")
    o.write("namespace SilentHillPC_Launcher\n{\n")
    o.write("    /// <summary>Every map message of the USA script by its language-pack key, with\n")
    o.write("    /// the control codes stripped for display. A voice file for a key is\n")
    o.write("    /// gamedata/load/XA/msg_&lt;key with '_' for '.'&gt;.wav (pc_msg_voice.c).</summary>\n")
    o.write("    internal static class MsgTable\n    {\n")
    o.write("        public struct Item\n        {\n            public string Key;\n            public string Text;\n")
    o.write("            public Item(string k, string t) { Key = k; Text = t; }\n        }\n\n")
    o.write("        public static readonly Item[] Items = new Item[]\n        {\n")
    for _, _, key, text in items:
        o.write("            new Item(%s, %s),\n" % (cs(key), cs(text)))
    o.write("        };\n    }\n}\n")
print("wrote", out, len(items), "items")
