#!/usr/bin/env python3
"""Generate pc_port/src/map7_s03_boss_motion.c — the final-boss projectile
motion-script data block (PSX 0x800EC018..0x800EC758), ported with PSX->PC
pointer relocation.

Why hand-generated (not the normal extractor): this region interleaves
- flat 16-byte velocity structs (s_800F3D48_0_0: all s16/u16, no pointers):
  D_800EC018[26], an unnamed vblk2[36] (contains the named sentinels
  D_800EC34C @idx5 and D_800EC3EC @idx15), D_800EC798[7]
- two s32 arrays D_800EC758[3], D_800EC764[3]
- pointer-bearing script arrays (s_800F3D48_0 = {s32 field_0; ptr next_4;
  s32 field_8}, 12B PSX / 24B PC): D_800EC1B8[27] and a CONTIGUOUS pool
  D_800EC53C/5A8/614/680/6EC (9 each = 45) that the boss indexes ACROSS symbol
  bounds via &D_800EC680[rand 0..15], so they must stay adjacent in memory.
The script next_4 fields hold PSX addresses (0x800EC...) that must be relocated
to the PC objects. Zero-stubbed, the walk had no valid links/terminators ->
NULL-deref crash the instant the boss attacks (incubator.log / incubus.log).

Output uses local typedefs (no game header) so the array/scalar/type
mismatches vs the externs stay link-only, exactly like the existing
emit_map7_d800ed274 emitter.
"""
import sys, struct, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import extract_map_data as E

OUT = E.REPO_ROOT / "pc_port" / "src" / "map7_s03_boss_motion.c"

def main():
    lb, _, _ = E.parse_sym_file(E.SYM_DIR / "sym.map7_s03.txt")
    b = open(E.bin_path_for_map("map7_s03"), "rb").read()

    def ofs(va): return va - lb
    def vec16(va):  # 4x s32 (matches VECTOR; bytes also valid as s_800F3D48_0_0 s16x8)
        return struct.unpack_from("<4i", b, ofs(va))
    def s32(va): return struct.unpack_from("<i", b, ofs(va))[0]
    def u32(va): return struct.unpack_from("<I", b, ofs(va))[0]

    # ---- region map ----
    VBLK1 = (0x800EC018, 26)   # D_800EC018[26]
    SCR1  = (0x800EC1B8, 27)   # D_800EC1B8[27]
    VBLK2 = (0x800EC2FC, 36)   # unnamed; D_800EC34C@+5, D_800EC3EC@+15
    POOL  = 0x800EC53C         # 45 entries: 53C/5A8/614/680/6EC each 9
    POOL_SYMS = [("D_800EC53C", 0x800EC53C), ("D_800EC5A8", 0x800EC5A8),
                 ("D_800EC614", 0x800EC614), ("D_800EC680", 0x800EC680),
                 ("D_800EC6EC", 0x800EC6EC)]
    POOL_END = 0x800EC758
    S32A = [("D_800EC758", 0x800EC758, 3), ("D_800EC764", 0x800EC764, 3)]
    VBLK3 = (0x800EC798, 7)    # D_800EC798[7]

    # vblk2 element name for a given va (named sentinels or synthetic)
    def vblk2_name(va):
        idx = (va - VBLK2[0]) // 16
        if va == 0x800EC34C: return "D_800EC34C"
        if va == 0x800EC3EC: return "D_800EC3EC"
        return "s_velB_%02d" % idx

    # resolve a PSX next_4 address -> C address expression
    def ref(p):
        if p == 0:
            return "(void*)0"
        if VBLK1[0] <= p < VBLK1[0] + VBLK1[1]*16:
            return "(void*)&D_800EC018[%d]" % ((p - VBLK1[0]) // 16)
        if SCR1[0] <= p < SCR1[0] + SCR1[1]*12:
            return "(void*)&D_800EC1B8[%d]" % ((p - SCR1[0]) // 12)
        if VBLK2[0] <= p < VBLK2[0] + VBLK2[1]*16:
            return "(void*)&%s" % vblk2_name(p)
        if POOL <= p < POOL_END:
            # one backing array; global index across the 45-entry pool
            return "(void*)&D_800EC53C[%d]" % ((p - POOL) // 12)
        if VBLK3[0] <= p < VBLK3[0] + VBLK3[1]*16:
            return "(void*)&D_800EC798[%d]" % ((p - VBLK3[0]) // 16)
        raise SystemExit("unresolved next_4 target 0x%08X" % p)

    out = []
    out.append("/* GENERATED by pc_port/tools/gen_map7_s03_boss_motion.py — do not edit by hand.\n"
               " * Final-boss projectile motion scripts (map7_s03 0x800EC018..0x800EC758),\n"
               " * PSX->PC pointer-relocated. Replaces the zero-stubs that crashed both boss\n"
               " * variants the instant they attacked (incubator.log / incubus.log). */\n")
    out.append("typedef struct { int a, b, c, d; } sh_vel16;          /* 16B flat velocity (s_800F3D48_0_0) */\n")
    out.append("typedef struct { int field_0; void* next_4; int field_8; } sh_scr; /* s_800F3D48_0 (12B PSX, 24B LP64 PC, 12B ILP32 PC) */\n")
    # The pool offset aliases below index by ELEMENT, so the asm byte stride must
    # track sizeof(sh_scr), which depends on pointer width (24B on LP64, 12B on
    # ILP32). Pick the stride at preprocess time and stringize it into the asm.
    out.append("#if defined(__SIZEOF_POINTER__) && __SIZEOF_POINTER__ == 4\n")
    out.append("#define SH_SCR_SZ 12\n")
    out.append("#else\n")
    out.append("#define SH_SCR_SZ 24\n")
    out.append("#endif\n")
    out.append("#define SH_STR2(x) #x\n")
    out.append("#define SH_STR(x) SH_STR2(x)\n")
    out.append("_Static_assert(sizeof(sh_scr) == SH_SCR_SZ, \"sh_scr size must match SH_SCR_SZ for the pool offset aliases\");\n")
    out.append("_Static_assert(sizeof(sh_vel16) == 16, \"sh_vel16 must be 16B\");\n\n")

    # ---- flat velocity D_800EC018[26] ----
    out.append("sh_vel16 D_800EC018[26] = {\n")
    for i in range(26):
        v = vec16(VBLK1[0] + i*16)
        out.append("    { %d, %d, %d, %d },\n" % v)
    out.append("};\n\n")

    # ---- vblk2: individual statics (referenced only via next_4) ----
    out.append("/* vblk2 velocity structs (0x800EC2FC..0x800EC53C); D_800EC34C/3EC are\n"
               " * the sentinels game code address-compares. */\n")
    for i in range(VBLK2[1]):
        va = VBLK2[0] + i*16
        nm = vblk2_name(va)
        v = vec16(va)
        out.append("sh_vel16 %s = { %d, %d, %d, %d };\n" % (nm, v[0], v[1], v[2], v[3]))
    out.append("\n")

    # ---- D_800EC798[7] ----
    out.append("sh_vel16 D_800EC798[7] = {\n")
    for i in range(VBLK3[1]):
        v = vec16(VBLK3[0] + i*16)
        out.append("    { %d, %d, %d, %d },\n" % v)
    out.append("};\n\n")

    # ---- s32 arrays ----
    for nm, a, n in S32A:
        vals = ", ".join(str(s32(a + j*4)) for j in range(n))
        out.append("int %s[%d] = { %s };\n" % (nm, n, vals))
    out.append("\n")

    # ---- script D_800EC1B8[27] ----
    def emit_script(name, start, count):
        out.append("sh_scr %s[%d] = {\n" % (name, count))
        for i in range(count):
            va = start + i*12
            f0 = s32(va); p4 = u32(va+4); f8 = s32(va+8)
            out.append("    { %d, %s, %d },\n" % (f0, ref(p4), f8))
        out.append("};\n")

    emit_script("D_800EC1B8", SCR1[0], SCR1[1])

    # Contiguous 45-entry pool as ONE array (the boss does &D_800EC680[0..15],
    # walking ACROSS the symbol boundaries). Separate arrays get 16-aligned and
    # gap by 8 bytes, breaking that; so emit one array + exact offset aliases.
    out.append("\n")
    emit_script("D_800EC53C", POOL, 45)
    out.append("\n/* Offset aliases into the single pool array (exact, no padding). The byte\n"
               " * stride is SH_SCR_SZ (sizeof sh_scr) so this is correct on LP64 and ILP32. */\n")
    for nm, a in POOL_SYMS:
        if a == POOL:
            continue
        entry = (a - POOL) // 12          # PSX entry index
        out.append('__asm__(".global %s\\n.set %s, D_800EC53C+" SH_STR(%d*SH_SCR_SZ) "\\n");\n' % (nm, nm, entry))
    out.append("\n")

    OUT.write_text("".join(out), encoding="utf-8")
    print("wrote", OUT, "(%d bytes)" % OUT.stat().st_size)

if __name__ == "__main__":
    main()
