"""Emit the launcher's RuCharsets.cs and JpnMsgMap.cs from the game's own
tables (pc_port/src/lang_ru.c, pc_port/src/lang_jpn_msgmap.inc) so the Voices
tool decodes a fan-patched Russian disc's text, and maps a Japanese disc's
message indices onto the US ones, exactly the way the game does.

Run after either source changes:
    python pc_port/tools/gen_launcher_lang_tables.py
"""
import os, re
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
out_dir = os.path.join(root, "pc_port/launcher/SilentHillPC_Launcher")

def read(p):
    return open(os.path.join(root, p), encoding="utf-8").read()

# ---- Russian charsets --------------------------------------------------------
src = read("pc_port/src/lang_ru.c")
src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
# Byte lists shared by a patch's upper and lower case live in `#define RU_X_BYTES \`
# continuation macros; expand them so every charset reads as two literal arrays.
for m in re.finditer(r"#define (RU_\w+_BYTES)\s*\\\n((?:[^\n]*\\\n)*[^\n]*)", src):
    body = m.group(2).replace("\\\n", "\n")
    src = src.replace(m.group(1) + ",", body + ",").replace(m.group(1) + "\n", body + "\n")
charsets = []
for m in re.finditer(r"static const s_RuCharset s_Charset_(\w+)\s*=\s*\{\s*\"([^\"]+)\"\s*,\s*(0x[0-9A-Fa-f]+)u?\s*,\s*\{([^}]*)\}\s*,\s*\{([^}]*)\}", src):
    up = [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+", m.group(4))]
    lo = [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+", m.group(5))]
    assert len(up) == 33 and len(lo) == 33, m.group(1)
    charsets.append((m.group(2), int(m.group(3), 0), up, lo))
assert charsets, "no charsets parsed"

with open(os.path.join(out_dir, "RuCharsets.cs"), "w", encoding="utf-8-sig", newline="\r\n") as o:
    o.write("// GENERATED by pc_port/tools/gen_launcher_lang_tables.py from pc_port/src/lang_ru.c. Do not edit.\n")
    o.write("namespace SilentHillPC_Launcher\n{\n")
    o.write("    /// <summary>Byte encodings of the known Russian fan patches, keyed by the FNV-1a\n")
    o.write("    /// hash of the disc's FONT16.TIM (the repainted atlas). Up/Lo hold the byte each\n")
    o.write("    /// patch writes for А..Я / а..я (0 = the atlas has no such cell).</summary>\n")
    o.write("    internal static class RuCharsets\n    {\n")
    o.write("        public const string Letters = \"АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ\";\n")
    o.write("        public struct Charset\n        {\n            public string Id;\n            public uint FontHash;\n            public byte[] Up;\n            public byte[] Lo;\n")
    o.write("            public Charset(string id, uint hash, byte[] up, byte[] lo) { Id = id; FontHash = hash; Up = up; Lo = lo; }\n        }\n\n")
    o.write("        public static readonly Charset[] All = new Charset[]\n        {\n")
    for cid, h, up, lo in charsets:
        o.write("            new Charset(\"%s\", 0x%08X,\n" % (cid, h))
        o.write("                new byte[] { %s },\n" % ", ".join("0x%02X" % b for b in up))
        o.write("                new byte[] { %s }),\n" % ", ".join("0x%02X" % b for b in lo))
    o.write("        };\n    }\n}\n")
print("RuCharsets.cs:", len(charsets), "charsets")

# ---- Japanese index maps -------------------------------------------------------
inc = read("pc_port/src/lang_jpn_msgmap.inc")
arrays = {}
for m in re.finditer(r"static const short (JPNMSG_\w+)\[(\d+)\]\s*=\s*\{([^}]*)\}", inc):
    vals = [int(x) for x in re.findall(r"-?\d+", m.group(3))]
    assert len(vals) == int(m.group(2)), m.group(1)
    arrays[m.group(1)] = vals
regs = re.findall(r"\{\s*MapIdx_(\w+)\s*,\s*(JPNMSG_\w+)\s*,\s*(\d+)\s*\}", inc)
assert regs, "no map registry parsed"

with open(os.path.join(out_dir, "JpnMsgMap.cs"), "w", encoding="utf-8-sig", newline="\r\n") as o:
    o.write("// GENERATED by pc_port/tools/gen_launcher_lang_tables.py from pc_port/src/lang_jpn_msgmap.inc. Do not edit.\n")
    o.write("using System.Collections.Generic;\n\n")
    o.write("namespace SilentHillPC_Launcher\n{\n")
    o.write("    /// <summary>US message index -> Japanese disc table index for the maps whose\n")
    o.write("    /// tables differ (-1 = no Japanese counterpart). Maps not listed are 1:1.</summary>\n")
    o.write("    internal static class JpnMsgMap\n    {\n")
    o.write("        public static readonly Dictionary<string, short[]> Maps = new Dictionary<string, short[]>\n        {\n")
    for mapname, arr, count in regs:
        vals = arrays[arr]
        o.write("            { \"%s\", new short[] { %s } },\n" % (mapname, ", ".join(str(v) for v in vals)))
    o.write("        };\n    }\n}\n")
print("JpnMsgMap.cs:", len(regs), "maps")
