#!/usr/bin/env python3
"""Regenerate pc_port/src/kanji_font.inc from the Shinonome 16-dot JIS X 0208
bitmap font (Public Domain - Yasuyuki Furukawa / the efont project).

Source file: the `16/kanjic/font_src.bit` BDF from
  https://github.com/code4fukui/shinonome-font
(mirror of http://openlab.ring.gr.jp/efont/shinonome/). The repo's .bit
variant is plain BDF with `.`/`@` visual bitmap rows and `ENDCHAR # <name>`
comments; ENCODING values are JIS X 0208 codes as decimals.

Usage: python3 make_kanji_font.py path/to/font_src.bit

Output format (consumed by pc_port/src/pc_kanji.c):
  KANJI_FONT_IDX[(ku-1)*94 + (ten-1)] -> glyph number (0xFFFF = absent)
  KANJI_FONT_BITS[glyph*32 .. +32]    -> 16 rows x 2 bytes, MSB-first, 1bpp
"""
import sys

def main(src):
    glyphs = {}
    cur = None
    rows = None
    for line in open(src, encoding='utf-8', errors='replace'):
        line = line.rstrip('\r\n')
        if line.startswith("ENCODING "):
            cur = int(line.split()[1])
            rows = None
        elif line == "BITMAP":
            rows = []
        elif rows is not None:
            if line.startswith("ENDCHAR"):
                if cur is not None and len(rows) >= 16:
                    data = bytearray()
                    for r in rows[:16]:
                        v = 0
                        for i, ch in enumerate(r[:16]):
                            if ch != '.':
                                v |= 0x8000 >> i
                        data += bytes([v >> 8, v & 0xFF])
                    glyphs[cur] = bytes(data)
                rows = None
            else:
                rows.append(line)

    idx = [0xFFFF] * (94 * 94)
    blob = bytearray()
    gcount = 0
    for code in sorted(glyphs):
        ku = (code >> 8) - 0x20
        ten = (code & 0xFF) - 0x20
        if not (1 <= ku <= 94 and 1 <= ten <= 94):
            continue
        idx[(ku - 1) * 94 + (ten - 1)] = gcount
        blob += glyphs[code]
        gcount += 1

    out = "C:/Claude/silenthill/silent-hill-decomp/pc_port/src/kanji_font.inc"
    with open(out, "w") as f:
        f.write("/* Generated by pc_port/tools/make_kanji_font.py from the Shinonome 16-dot\n")
        f.write(" * JIS X 0208 bitmap font (Public Domain - Yasuyuki Furukawa / the efont\n")
        f.write(" * project, http://openlab.ring.gr.jp/efont/). %d glyphs, 16x16 1bpp,\n" % gcount)
        f.write(" * 32 bytes per glyph (16 rows x 2 bytes, MSB-first).\n")
        f.write(" * Index: KANJI_FONT_IDX[(ku-1)*94 + (ten-1)] = glyph number, 0xFFFF = absent. */\n")
        f.write("static const unsigned short KANJI_FONT_IDX[94*94] = {\n")
        for i in range(0, 94 * 94, 16):
            f.write("    " + ",".join("0x%04X" % v for v in idx[i:i + 16]) + ",\n")
        f.write("};\n")
        f.write("static const unsigned char KANJI_FONT_BITS[%d] = {\n" % len(blob))
        for i in range(0, len(blob), 24):
            f.write("    " + ",".join("0x%02X" % b for b in blob[i:i + 24]) + ",\n")
        f.write("};\n")
    print("wrote", out, "-", gcount, "glyphs,", len(blob), "bytes")

if __name__ == "__main__":
    main(sys.argv[1])
