#!/usr/bin/env python3
"""Build pc_port/src/kanji_font_cn.inc: the Chinese glyph block for NTSC-J.

The Chinese fan translation of SH1 ships a patched PSX BIOS whose kanji ROM
holds Chinese glyphs, and a disc whose text writes the JIS kuten codes those
glyphs sit at. The port has no BIOS -- it rasterizes from its own embedded
Shinonome JIS font -- so the same disc renders as mojibake: right kuten, wrong
glyphs.

The BIOS font is 3276 glyphs of 16x15 (30 bytes, MSB-first). Its layout is
mixed: indices 0..250 are kana/symbols in a custom order, and 251..3258 are the
translation's own characters laid out in kuten order over ku=16..47:

    bios_idx = (ku - 16) * 94 + (ten - 1) + 251

That mapping, and the extraction of CN_BIOS_font_16x15.bin from the patched
BIOS, are the work of the fan who got Chinese running on the port first
(SH1PC_CN_Font_Patch_Beta); this script only repackages the result so the port
can carry BOTH fonts and switch at runtime instead of overwriting the Japanese
one. Every glyph the mapping touches falls in one contiguous run of the port's
glyph blob, so only that run is emitted.

Usage:
    python make_kanji_font_cn.py CN_BIOS_font_16x15.bin
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
JP_INC = os.path.join(HERE, '..', 'src', 'kanji_font.inc')
OUT = os.path.join(HERE, '..', 'src', 'kanji_font_cn.inc')

BIOS_GLYPH_BYTES = 30
BIOS_ROWS = 15
BIOS_KANJI_BASE = 251
KU_LO, KU_HI = 16, 47


def load_jp_index(path):
    s = io.open(path, encoding='utf-8', errors='replace').read()
    m = re.search(r'KANJI_FONT_IDX\[94\*94\]\s*=\s*\{(.*?)\};', s, re.S)
    return [int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{4})', m.group(1))]


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    idx = load_jp_index(JP_INC)
    cn = open(sys.argv[1], 'rb').read()
    n_bios = len(cn) // BIOS_GLYPH_BYTES

    glyphs = {}
    for ku in range(KU_LO, KU_HI + 1):
        for ten in range(1, 95):
            slot = (ku - 1) * 94 + (ten - 1)
            pos = idx[slot]
            if pos == 0xFFFF:
                continue
            bi = (ku - KU_LO) * 94 + (ten - 1) + BIOS_KANJI_BASE
            if not (0 <= bi < n_bios):
                continue
            g = cn[bi * BIOS_GLYPH_BYTES: bi * BIOS_GLYPH_BYTES + BIOS_GLYPH_BYTES]
            glyphs[pos] = g + b'\x00\x00'   # 16x15 -> 16x16, blank bottom row

    first, last = min(glyphs), max(glyphs)
    count = last - first + 1
    missing = [g for g in range(first, last + 1) if g not in glyphs]
    if missing:
        sys.exit(f'glyph run {first}..{last} has {len(missing)} holes; '
                 'the block is no longer contiguous, teach pc_kanji.c a table')

    blob = bytearray()
    for g in range(first, last + 1):
        blob += glyphs[g]

    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by pc_port/tools/make_kanji_font_cn.py from the Chinese fan\n'
                ' * translation\'s patched PSX BIOS kanji ROM. Glyph bitmaps only: the kuten\n'
                ' * index table in kanji_font.inc is shared, because the translation writes the\n'
                ' * same JIS kuten codes and only redefines what is drawn at them (ku 16..47).\n'
                ' * The replaced glyphs form one contiguous run of the shared blob, so this is\n'
                ' * that run alone rather than a second whole font.\n'
                f' * {count} glyphs, 16x16 1bpp, 32 bytes per glyph (16 rows x 2 bytes, MSB-first). */\n')
        f.write(f'#define KANJI_CN_FIRST {first}\n')
        f.write(f'#define KANJI_CN_COUNT {count}\n')
        f.write(f'static const unsigned char KANJI_FONT_BITS_CN[{len(blob)}] = {{\n')
        for i in range(0, len(blob), 24):
            f.write('    ' + ','.join('0x%02X' % b for b in blob[i:i + 24]) + ',\n')
        f.write('};\n')
    print(f'wrote {OUT}: glyphs {first}..{last} ({count}), {len(blob)} bytes')


if __name__ == '__main__':
    main()
