#!/usr/bin/env python3
"""Turn zh.pack into zh.lang, so Chinese works on any disc.

zh.pack was built for a Japanese disc: its map tables are in the DISC's message
order, because the only caller was the NTSC-J path, which applies the port's
US->JP index map to them. That makes it unusable anywhere else -- a PAL or US
disc has no such path, and Chinese was simply not on the Language row there.

This re-keys the same text by US message index, the way ja.lang is keyed, so
the ordinary pack path serves it on every disc with no loader change. Nothing
is transcoded: the stored bytes are the disc's own JIS kuten codes, whose
glyphs the port's embedded Chinese font (kanji_font_cn.inc) redefines, which is
why the pack declares !font=chinese rather than sjis -- same encoding, other
glyph table.

No disc needed; zh.pack already holds everything (item names, descriptions, map
messages, menu fields).

Usage:  python make_zh_lang.py
"""
import io
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import make_jp_pack as jp  # noqa: E402  (msg_maps, map_order, menu_table, copy_entry, esc)

PACK = os.path.join(HERE, '..', 'assets', 'gamedata', 'lang', 'zh.pack')
OUT = os.path.join(HERE, '..', 'assets', 'gamedata', 'lang', 'zh.lang')

MAGIC = 0x485A4853
NO_STR = 0xFFFFFFFF
HDR = '<7I'


def load():
    d = io.open(PACK, 'rb').read()
    magic, version, itemCount, mapCount, blobOff, blobSize, menuCount = \
        struct.unpack_from(HDR, d, 0)
    if magic != MAGIC:
        sys.exit('error: %s is not a zh.pack (magic 0x%08X)' % (PACK, magic))

    def string(off):
        if off == NO_STR or off >= blobSize:
            return None
        end = d.index(bytes([0]), blobOff + off)
        return d[blobOff + off:end]

    o = struct.calcsize(HDR)
    names = struct.unpack_from('<%dI' % itemCount, d, o)
    o += 4 * itemCount
    descs = struct.unpack_from('<%dI' % itemCount, d, o)
    o += 4 * itemCount
    mapTabs = struct.unpack_from('<%dI' % mapCount, d, o)
    o += 4 * mapCount
    menus = [struct.unpack_from('<2I', d, o + 8 * i) for i in range(menuCount)]

    maps = []
    for t in mapTabs:
        if t == 0 or t == NO_STR:
            maps.append([])
            continue
        n = struct.unpack_from('<I', d, t)[0]
        offs = struct.unpack_from('<%dI' % n, d, t + 4)
        maps.append([string(x) for x in offs])

    return {
        'names': [string(x) for x in names],
        'descs': [string(x) for x in descs],
        'maps': maps,
        'menus': [(string(off) if ln == 0 else
                   d[blobOff + off:blobOff + off + ln]) if off != NO_STR else None
                  for off, ln in menus],
        'menuLens': [ln for _off, ln in menus],
        'blob': d,
        'blobOff': blobOff,
    }


def main():
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

    pack = load()
    order = jp.map_order()
    idxmaps = jp.msg_maps()
    entries = []

    # Story: the pack's tables are in disc (JP) order, so walk the US index and
    # pull the JP one the port's own map names -- exactly what the NTSC-J path
    # does at runtime, done once here instead.
    for mapIdx, mapname in enumerate(order):
        if mapname is None or mapIdx >= len(pack['maps']):
            continue
        msgs = pack['maps'][mapIdx]
        if not msgs:
            continue
        idxmap = idxmaps.get(mapname)
        count = len(idxmap) if idxmap else len(msgs)
        for us in range(count):
            zh = idxmap[us] if idxmap else us
            if zh < 0 or zh >= len(msgs) or not msgs[zh]:
                continue
            key = ('COMMON.%d' % us) if us < jp.COMMON_MSG_COUNT \
                else ('%s.%d' % (mapname, us))
            entries.append((key, msgs[zh]))

    # Menus: the pack stores the same fixed-width field the overlay holds, so
    # the loader's own trim applies unchanged.
    for i, (us, _f, _o, length) in enumerate(jp.menu_table()):
        if i >= len(pack['menus']):
            break
        raw = pack['menus'][i]
        if not raw:
            continue
        v = jp.copy_entry(raw, 0, length if length else 0) if length \
            else jp.copy_entry(raw + bytes([0]), 0, 0)
        if v:
            entries.append(('MENU.' + us.replace(' ', '_').replace('=', '-'), v))

    for i, v in enumerate(pack['names']):
        if v:
            entries.append(('ITEM_NAME.%d' % i, v))
    for i, v in enumerate(pack['descs']):
        if v:
            entries.append(('ITEM_DESC.%d' % i, v))

    seen = set()
    menus = story = items = 0
    with io.open(OUT, 'wb') as f:
        f.write(b'# Silent Hill PC -- language pack (generated by make_zh_lang.py)\n')
        f.write(b'# Chinese, re-keyed from zh.pack by US message index so any disc\n')
        f.write(b'# can offer it. Values are the disc\'s own JIS kuten codes; the\n')
        f.write(b'# port\'s embedded Chinese font redefines those glyphs.\n')
        f.write(b'!font=chinese\n!code=zh\n!name=Chinese\n!menu=Chinese\n')
        for key, v in entries:
            if key in seen:
                continue
            seen.add(key)
            f.write(key.encode('ascii') + b'=' + jp.esc(v) + b'\n')
            if key.startswith('MENU.'):
                menus += 1
            elif key.startswith('ITEM_'):
                items += 1
            else:
                story += 1
    print('%d entries (story %d, menu %d, item %d), %s KB'
          % (len(seen), story, menus, items,
             '{:,}'.format(os.path.getsize(OUT) // 1024)))
    print('WROTE:', os.path.normpath(OUT))


if __name__ == '__main__':
    main()
