#!/usr/bin/env python3
"""Build pc_port/src/font_ru.inc: the Cyrillic FONT16 atlas for the Russian pack.

Russian ships as a PC-side language pack, so it has to bring its own glyphs the
way Polish does -- but Polish needed seven letterforms and Russian needs
sixty-six, which the retail PAL atlas has nowhere to put. The consolgames.ru
2011 PAL translation already solved exactly this: it repaints the whole 21x6
atlas, putting uppercase Cyrillic over the Latin capitals and the lowercase
alphabet over the accent block, and the port ALREADY carries the byte table for
that layout (s_Charset_ConsolGames in lang_ru.c, derived and verified from the
disc's own text). So the pack copies that atlas wholesale and the existing
encoder addresses it unchanged -- no new per-letter mapping to get wrong.

Both halves come off the same disc: the 126 cells of 1ST/FONT16.TIM, and the
126 glyph advances the translation retuned, from the decrypted BODYPROG at the
same offset the retail EUR table sits at (0x80025D6C).

Usage:
    python make_font_ru.py "<gamedata>/Silent Hill (PAL) russian.bin"
"""
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_zh_pack as disc  # noqa: E402  (raw-sector reader, overlay LCG)

import re

REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(HERE, '..', 'src', 'font_ru.inc')

ATLAS_COLS, CELL_W, CELL_H, ROWS = 21, 12, 16, 6
CELL_COUNT = ATLAS_COLS * ROWS            # 126
WIDTHS_OFF = 0x120C                       # BODYPROG file offset of the 126 advances
CONSOLGAMES_FNV = 0x7D67AF89              # FONT16.TIM hash, must match lang_ru.c
CELL_E_OBERT = 87                         # uppercase Э as the disc draws it
CELL_E_ALT   = 90                         # ... and where the pack puts it instead

FT = open(os.path.join(REPO, 'src', 'main', 'filetable.c.EUR.inc'),
          encoding='utf-8', errors='replace').read()


def ft_entry(tag):
    m = re.search(r'\{\s*(0x[0-9a-fA-F]+),\s*(\d+),.*?//\s*%s' % re.escape(tag), FT)
    return int(m.group(1), 16), int(m.group(2))


def fnv1a(b):
    h = 2166136261
    for x in b:
        h = ((h ^ x) * 16777619) & 0xFFFFFFFF
    return h


def tim_pixels(tim):
    assert tim[:4] == b'\x10\x00\x00\x00', 'not a TIM'
    flags = struct.unpack_from('<I', tim, 4)[0]
    off = 8
    if flags & 8:
        off += struct.unpack_from('<I', tim, off)[0]
    plen, _px, _py, pw, ph = struct.unpack_from('<IHHHH', tim, off)
    return pw, ph, tim[off + 12: off + plen]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = sys.argv[1]

    lba, blocks = ft_entry('1ST/FONT16.TIM')
    tim = disc.read_disc_file(path, lba, blocks * 256)
    if tim is None:
        sys.exit('error: could not read FONT16.TIM (is this a raw 2352-byte image?)')
    h = fnv1a(tim)
    if h != CONSOLGAMES_FNV:
        sys.exit('error: FONT16 hash %08X is not the consolgames.ru atlas (%08X).\n'
                 'The byte table in lang_ru.c only addresses that one.' % (h, CONSOLGAMES_FNV))

    pw, ph, data = tim_pixels(tim)
    stride = pw * 2
    if pw * 4 < ATLAS_COLS * CELL_W or ph < ROWS * CELL_H:
        sys.exit('error: atlas is %dx%d, need %dx%d' % (pw * 4, ph, ATLAS_COLS * CELL_W, ROWS * CELL_H))

    # One cell = 16 rows x 12 nibbles, packed two pixels per byte, low nibble
    # first -- the order font_region.c's PixGet/PixSet use.
    cells = []
    for cell in range(CELL_COUNT):
        cx, cy = (cell % ATLAS_COLS) * CELL_W, (cell // ATLAS_COLS) * CELL_H
        out = bytearray()
        for r in range(CELL_H):
            for c in range(0, CELL_W, 2):
                lo = data[(cy + r) * stride + ((cx + c) >> 1)]
                hi = data[(cy + r) * stride + ((cx + c + 1) >> 1)]
                out.append((lo & 0x0F) | ((hi >> 4) << 4))
        cells.append(bytes(out))

    # Uppercase Э sits on cell 87, whose byte is 0x7E -- which this engine reads
    # as the '~' control-code marker (the fan disc sidesteps that by using {}
    # markers of its own). Give it a second home on cell 90, a duplicate ф the
    # charset never addresses, and lang_ru.c's pack encoder emits that instead.
    cells[CELL_E_ALT] = cells[CELL_E_OBERT]

    lba, blocks = ft_entry('1ST/BODYPROG.BIN')
    body = disc.fs_decrypt_overlay(disc.read_disc_file(path, lba, blocks * 256))
    widths = list(body[WIDTHS_OFF:WIDTHS_OFF + CELL_COUNT])
    widths[CELL_E_ALT] = widths[CELL_E_OBERT]
    if max(widths) > CELL_W + 4:
        sys.exit('error: advances at 0x%X exceed the cell; wrong offset or disc' % WIDTHS_OFF)

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* SPDX-License-Identifier: GPL-3.0-or-later */\n')
        f.write('/* Generated by pc_port/tools/make_font_ru.py from the consolgames.ru 2011\n'
                ' * PAL translation (FONT16.TIM hash %08X). The whole %d-cell 21x6 atlas and\n'
                ' * its retuned glyph advances, so the Russian pack draws through the byte\n'
                ' * table lang_ru.c already carries for this layout. Cells are 16 rows of 12\n'
                ' * 4bpp pixels, two per byte, low nibble first. */\n' % (CONSOLGAMES_FNV, CELL_COUNT))
        f.write('static const unsigned char FONT_RU_WIDTHS[%d] = {\n' % CELL_COUNT)
        for i in range(0, CELL_COUNT, 21):
            f.write('    ' + ', '.join('%2d' % w for w in widths[i:i + 21]) + ',\n')
        f.write('};\n\n')
        f.write('static const unsigned char FONT_RU_ATLAS[%d][%d] = {\n' % (CELL_COUNT, CELL_H * CELL_W // 2))
        for i, cell in enumerate(cells):
            f.write('    { ' + ','.join('0x%02X' % b for b in cell) + ' }, /* %d */\n' % i)
        f.write('};\n')

    print('FONT16 %08X ok; wrote %d cells + %d advances' % (h, CELL_COUNT, CELL_COUNT))
    print('WROTE:', os.path.normpath(OUT))


if __name__ == '__main__':
    main()
