# Generates sh_build_info.h with the current git hash + dirty marker.
# Only rewrites the file when the content changes, so incremental builds
# don't recompile main_pc.c needlessly.

execute_process(
    COMMAND git -C "${GIT_DIR}" rev-parse --short=9 HEAD
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT GIT_HASH)
    set(GIT_HASH "unknown")
endif()

# NOTE: no dirty-tree marker — the git CMake invokes can differ from the
# developer's (autocrlf mismatch reports CRLF files as always-modified),
# which made every build read "+dirty". The hash is what triage needs.
string(TIMESTAMP BUILD_STAMP "%Y-%m-%d %H:%M:%S")

# --- Win32 version resource (sh_version.h) ----------------------------------
# Build field = git commit count (monotonic), and the git hash pins the exact
# source. Written only when that content CHANGES, so the exe relinks per commit
# rather than every build — important because the game is often run from the
# build dir (a locked exe makes a relink fail). Only app.rc includes this.
if(VER_FILE)
    execute_process(
        COMMAND git -C "${GIT_DIR}" rev-list --count HEAD
        OUTPUT_VARIABLE GIT_COUNT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT GIT_COUNT)
        set(GIT_COUNT 0)
    endif()
    set(VER_CONTENT "/* Auto-generated by gen_build_info.cmake — do not edit. */
#define SH_VER_MAJOR     1
#define SH_VER_MINOR     0
#define SH_VER_BUILD     ${GIT_COUNT}
#define SH_VER_REV       0
#define SH_VER_FILE_STR  \"1.0.${GIT_COUNT} (${GIT_HASH})\"
#define SH_VER_PROD_STR  \"1.0\"
")
    set(VER_WRITE TRUE)
    if(EXISTS "${VER_FILE}")
        file(READ "${VER_FILE}" VER_OLD)
        if(VER_OLD STREQUAL VER_CONTENT)
            set(VER_WRITE FALSE)
        endif()
    endif()
    if(VER_WRITE)
        file(WRITE "${VER_FILE}" "${VER_CONTENT}")
    endif()
endif()

set(CONTENT "/* Auto-generated by gen_build_info.cmake — do not edit. */
#define SH_BUILD_GIT_HASH \"${GIT_HASH}\"
#define SH_BUILD_STAMP    \"${BUILD_STAMP}\"
")

if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" OLD_CONTENT)
    # Compare only the hash line; the timestamp alone shouldn't force rebuilds.
    string(REGEX MATCH "SH_BUILD_GIT_HASH \"[^\"]*\"" OLD_HASH "${OLD_CONTENT}")
    string(REGEX MATCH "SH_BUILD_GIT_HASH \"[^\"]*\"" NEW_HASH "${CONTENT}")
    if(OLD_HASH STREQUAL NEW_HASH)
        return()
    endif()
endif()

file(WRITE "${OUT_FILE}" "${CONTENT}")
