# Generates sh_build_info.h with the current git hash + dirty marker.
# Only rewrites the file when the content changes, so incremental builds
# don't recompile main_pc.c needlessly.

execute_process(
    COMMAND git -C "${GIT_DIR}" rev-parse --short=9 HEAD
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT GIT_HASH)
    set(GIT_HASH "unknown")
endif()

execute_process(
    COMMAND git -C "${GIT_DIR}" status --porcelain --untracked-files=no
    OUTPUT_VARIABLE GIT_DIRTY_OUT
    ERROR_QUIET
)
if(GIT_DIRTY_OUT)
    set(GIT_HASH "${GIT_HASH}+dirty")
endif()

string(TIMESTAMP BUILD_STAMP "%Y-%m-%d %H:%M:%S")

set(CONTENT "/* Auto-generated by gen_build_info.cmake — do not edit. */
#define SH_BUILD_GIT_HASH \"${GIT_HASH}\"
#define SH_BUILD_STAMP    \"${BUILD_STAMP}\"
")

if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" OLD_CONTENT)
    # Compare only the hash line; the timestamp alone shouldn't force rebuilds.
    string(REGEX MATCH "SH_BUILD_GIT_HASH \"[^\"]*\"" OLD_HASH "${OLD_CONTENT}")
    string(REGEX MATCH "SH_BUILD_GIT_HASH \"[^\"]*\"" NEW_HASH "${CONTENT}")
    if(OLD_HASH STREQUAL NEW_HASH)
        return()
    endif()
endif()

file(WRITE "${OUT_FILE}" "${CONTENT}")
