/* AUTO-GENERATED by pc_port/tools/extract_map_data.py — do not edit.
 * Source: disc_extract/VIN/MAP2_S00.BIN
 * Map: map2_s00
 *
 * Per-map cutscene data extracted from the original PSX map overlay binary.
 * In the upstream decomp these are `extern` declared in include/maps/map2/map2_s00.h
 * but their data lives only in the PSX overlay binary, not in C source.
 * This file provides them as local definitions so the map DLL is self-contained.
 */

#include <assert.h>  /* C11 static_assert macro */
#include "common.h"
#include "game.h"  /* VECTOR3 */

// 0x800F1A10  size 0x4 (4 bytes)
u16 g_Cutscene_MapMsgAudioCmds[2] = {
    0x104D, 0x1041
};

// 0x800F1A14  size 0x14 (20 bytes)
s16 g_Gfx_LockTimFileIdxs[10] = {
    1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 0, 0
};

// 0x800F2294  size 0x18 (24 bytes)
u8 g_Cutscene_MapMsgAudioIdx = 0x00;

