/* AUTO-GENERATED by pc_port/tools/extract_map_data.py — do not edit.
 * Source: disc_extract/VIN/MAP2_S00.BIN
 * Map: map2_s00
 *
 * Per-map data extracted from the original PSX map overlay binary.
 * In the upstream decomp these are `extern` declared in map headers but their
 * data lives only in the PSX overlay binary, not in C source.
 * This file provides them as local definitions so the map DLL is self-contained.
 */

#include <assert.h>  /* C11 static_assert macro */
#include "common.h"
#include "game.h"  /* VECTOR3, SVECTOR3 */

/* Minimal typedef for s_WorldObjectPose — full definition is in maps/shared.h.
 * Guarded so it doesn't conflict if a map's header is pulled in transitively. */
#ifndef S_WORLD_OBJECT_POSE_FWDDECL
#define S_WORLD_OBJECT_POSE_FWDDECL
typedef struct { VECTOR3 position; SVECTOR3 rotation_C; } s_WorldObjectPose;
#endif

// 0x800EE9BC  size 0x23 (35 bytes)
u8 LOADABLE_INVENTORY_ITEMS[35] = {
    0x20, 0x21, 0x22, 0x80, 0x81, 0x84, 0x85, 0x87, 0xA0, 0xA1, 0xA2, 0xA3, 0xC0, 0xC1, 0xC2, 0xE0,
    0xE1, 0x41, 0x42, 0x43, 0x44, 0x47, 0x48, 0x53, 0x54, 0x64, 0x4C, 0x65, 0x66, 0x6E, 0x82, 0xE2,
    0x58, 0x86, 0x00
};

// 0x800F1A10  size 0x4 (4 bytes)
u16 g_Cutscene_MapMsgAudioCmds[2] = {
    0x104D, 0x1041
};

// 0x800F1A14  size 0x14 (20 bytes)
s16 g_Gfx_LockTimFileIdxs[10] = {
    1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 0, 0
};

// 0x800F1A28  size 0x280 (640 bytes)
s_WorldObjectPose g_CommonWorldObjectPoses[32] = {
    { { -256081, 0, -133160 }, { 0, 1774, 0 } },
    { { 227737, 0, -142745 }, { 0, 102, 0 } },
    { { 226508, 0, -141926 }, { 0, 216, 0 } },
    { { 404930, -4710, -145612 }, { 0, 1228, 0 } },
    { { 396574, 0, -525926 }, { 0, 318, 0 } },
    { { 394854, 0, -529612 }, { 0, 273, 0 } },
    { { 462110, -4096, 897884 }, { 0, 0, 0 } },
    { { 481656, -3727, 898805 }, { 0, 341, 0 } },
    { { 473989, -4096, 886005 }, { 0, 682, 0 } },
    { { 462163, -4096, 1225150 }, { 0, 0, 0 } },
    { { 471646, -4096, 1213911 }, { 0, 147, 0 } },
    { { -1020928, -614, 591872 }, { 0, 682, 0 } },
    { { 758988, 0, 470220 }, { 0, 284, 0 } },
    { { -170598, -12697, 1421762 }, { 0, 1433, 0 } },
    { { -1019289, -614, 594841 }, { 0, 227, 0 } },
    { { -724357, 0, -130441 }, { 0, 0, 0 } },
    { { -763269, 0, -228724 }, { 0, 364, 0 } },
    { { -292896, -2580, -772722 }, { 0, 170, 0 } },
    { { -239435, 0, -599797 }, { 0, 420, 0 } },
    { { -399069, -4505, -211423 }, { 0, 1444, 0 } },
    { { -401031, -4096, -537804 }, { 0, 0, 0 } },
    { { 590254, -3121, 1562263 }, { 0, 0, 0 } },
    { { 593240, -3121, 1560174 }, { 0, 0, 0 } },
    { { -773734, -4710, 1538457 }, { 0, 0, 0 } },
    { { 86425, -4710, 72908 }, { 0, 0, 0 } },
    { { 601292, 2621, -392396 }, { 0, 1809, 0 } },
    { { 598630, 4259, -389120 }, { 0, 762, 0 } },
    { { 88453, -2490, 260038 }, { 0, 273, 0 } },
    { { 91885, -2490, 259993 }, { 0, 136, 0 } },
    { { -780083, 0, 1234739 }, { 0, 682, 0 } },
    { { -781516, 0, 1233715 }, { 0, 341, 0 } },
    { { 520847, -4096, 895422 }, { 0, 113, 0 } }
};

// 0x800F2294  size 0x18 (24 bytes)
u8 g_Cutscene_MapMsgAudioIdx = 0x00;

